apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: portal-tracks-apiproduct-reference-grant
  namespace: tracks
spec:
  from:
    - group: portal.gloo.solo.io
      kind: Portal
      namespace: default
  to:
    - group: portal.gloo.solo.io
      kind: ApiProduct