apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: oidc-atv
  namespace: tracks
spec:
  options:
    extauth:
      configRef:
        name: oauth-oidc-atv-auth
        namespace: default
    cors:
      allowOrigin:
        - http://localhost:4000
        - http://127.0.0.1:4000
        - http://portal.example.com
        - http://portal.example.com:8080
      allowHeaders:
        - Authorization
        - Content-Type
        - api-key
      allowMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowCredentials: true